//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxi.Persistencia.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maxi.Persistencia.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_Autenticar @Usuario, @Password .
        /// </summary>
        internal static string Autenticar {
            get {
                return ResourceManager.GetString("Autenticar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_CrearPassword @UserName, @Password.
        /// </summary>
        internal static string CrearPassword {
            get {
                return ResourceManager.GetString("CrearPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_EliminarProducto @idproducto.
        /// </summary>
        internal static string EliminarProducto {
            get {
                return ResourceManager.GetString("EliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_EliminarProveedor @idproveedor.
        /// </summary>
        internal static string EliminarProveedor {
            get {
                return ResourceManager.GetString("EliminarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_EliminarZona @idZona.
        /// </summary>
        internal static string EliminarZona {
            get {
                return ResourceManager.GetString("EliminarZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ListarProductos.
        /// </summary>
        internal static string GetAllProductos {
            get {
                return ResourceManager.GetString("GetAllProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ListarProveedores.
        /// </summary>
        internal static string GetAllProveedores {
            get {
                return ResourceManager.GetString("GetAllProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ListarZonas.
        /// </summary>
        internal static string GetAllZonas {
            get {
                return ResourceManager.GetString("GetAllZonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_BuscarProductoxId @idproducto.
        /// </summary>
        internal static string GetProductoById {
            get {
                return ResourceManager.GetString("GetProductoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_BuscarProveedorxId @idproveedor.
        /// </summary>
        internal static string GetProveedorById {
            get {
                return ResourceManager.GetString("GetProveedorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_BuscarZonaxId @idZona.
        /// </summary>
        internal static string GetZonaById {
            get {
                return ResourceManager.GetString("GetZonaById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_InsertarProducto @nombreProducto, @dimensiones, @unidadEmpaque, @precio.
        /// </summary>
        internal static string InsertProducto {
            get {
                return ResourceManager.GetString("InsertProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_InsertarProveedor @celular, @direccion, @emailContacto, @estado, @nit, @nombreContacto, @nroDocContacto, @razonSocial, @telefonoFijo, @tipoDocContacto.
        /// </summary>
        internal static string InsertProveedor {
            get {
                return ResourceManager.GetString("InsertProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_InsertarZona @nombreZona, @municipio, @estado, @valorCobro.
        /// </summary>
        internal static string InsertZona {
            get {
                return ResourceManager.GetString("InsertZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ActualizarProducto @idproducto, @nombreProducto, @dimensiones, @unidadEmpaque, @precio.
        /// </summary>
        internal static string UpdateProducto {
            get {
                return ResourceManager.GetString("UpdateProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ActualizarProveedor @idProveedor, @celular, @direccion, @emailContacto, @estado, @nit, @nombreContacto, @nroDocContacto, @razonSocial, @telefonoFijo, @tipoDocContacto,.
        /// </summary>
        internal static string UpdateProveedor {
            get {
                return ResourceManager.GetString("UpdateProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exec dbo.SP_ActualizarZona @idZona, @nombreZona, @municipio, @estado, @valorCobro.
        /// </summary>
        internal static string UpdateZona {
            get {
                return ResourceManager.GetString("UpdateZona", resourceCulture);
            }
        }
    }
}
